#pragma once

#define SCE_SYSTEM_PARAM_ID_LANG 1

#define SCE_SYSTEM_PARAM_LANG_JAPANESE       0
#define SCE_SYSTEM_PARAM_LANG_ENGLISH_US     1
#define SCE_SYSTEM_PARAM_LANG_FRENCH         2
#define SCE_SYSTEM_PARAM_LANG_SPANISH        3
#define SCE_SYSTEM_PARAM_LANG_GERMAN         4
#define SCE_SYSTEM_PARAM_LANG_ITALIAN        5
#define SCE_SYSTEM_PARAM_LANG_DUTCH          6
#define SCE_SYSTEM_PARAM_LANG_PORTUGUESE_PT  7
#define SCE_SYSTEM_PARAM_LANG_RUSSIAN        8
#define SCE_SYSTEM_PARAM_LANG_KOREAN         9
#define SCE_SYSTEM_PARAM_LANG_CHINESE_T      10
#define SCE_SYSTEM_PARAM_LANG_CHINESE_S      11
#define SCE_SYSTEM_PARAM_LANG_FINNISH        12
#define SCE_SYSTEM_PARAM_LANG_SWEDISH        13
#define SCE_SYSTEM_PARAM_LANG_DANISH         14
#define SCE_SYSTEM_PARAM_LANG_NORWEGIAN      15
#define SCE_SYSTEM_PARAM_LANG_PORTUGUESE_BR  16

#define SCE_APPUTIL_SAVEDATA_SLOT_SUBTITLE_MAXSIZE 128
#define SCE_APPUTIL_SAVEDATA_SLOT_TITLE_MAXSIZE    64

inline int sceAppUtilSystemParamGetInt(int paramId, int *value) {
    (void)paramId;
    if (value) *value = 0;
    return 0;
}
