#pragma once

typedef enum SceMsgDialogSystemMessageType {
    SCE_MSG_DIALOG_SYSMSG_TYPE_WAIT                        = 0,
    SCE_MSG_DIALOG_SYSMSG_TYPE_NOSPACE                     = 1,
    SCE_MSG_DIALOG_SYSMSG_TYPE_PROGRESS                    = 2,
    SCE_MSG_DIALOG_SYSMSG_TYPE_NOSPACE_CONTINUABLE         = 3,
    SCE_MSG_DIALOG_SYSMSG_TYPE_TRC_MIC_DISABLED            = 100,
    SCE_MSG_DIALOG_SYSMSG_TYPE_TRC_WIFI_REQUIRED_OPERATION   = 101,
    SCE_MSG_DIALOG_SYSMSG_TYPE_TRC_WIFI_REQUIRED_APPLICATION = 102,
    SCE_MSG_DIALOG_SYSMSG_TYPE_TRC_EMPTY_STORE             = 103
} SceMsgDialogSystemMessageType;
